import type { Opportunity } from './landing-types';

const d = (daysAgo: number) =>
  new Date(Date.now() - daysAgo * 86400000).toISOString().slice(0, 10);

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-1',
    title: 'ساخت واحد مسکونی — وثیقه ملکی',
    category: 'real_estate',
    targetAmount: 2_000_000_000,
    raisedAmount: 1_200_000_000,
    durationMonths: 12,
    repaymentPlan: 'MONTHLY',
    grossAPR: 22,
    netAPR: 18.5,
    GI: 3,
    guaranteePack: [
      { type: 'وثیقه ملکی', verified: true, valuationDate: '2026-01-10', coverageLevel: 120 },
    ],
    dossier: [
      { key: 'identity', label: 'احراز هویت', done: true, updatedAt: '2026-01-05' },
      { key: 'collateral', label: 'ثبت ضمانت', done: true, updatedAt: '2026-01-10' },
      { key: 'valuation', label: 'ارزش‌گذاری', done: true, updatedAt: '2026-01-10' },
      { key: 'contract', label: 'قرارداد آماده', done: true, updatedAt: '2026-01-12' },
    ],
    events: [
      { label: 'ثبت', date: d(45) },
      { label: 'تأیید', date: d(40) },
      { label: 'شروع تأمین', date: d(30) },
      { label: 'گزارش ۱', date: d(7) },
      { label: 'تسویه', date: '' },
    ],
    cashflowPreview: [
      { label: 'شروع تأمین', amount: 0, date: d(30) },
      { label: 'قسط ۱', amount: 180_000_000, date: '2026-04-01' },
      { label: 'قسط ۲', amount: 180_000_000, date: '2026-05-01' },
      { label: 'قسط ۳', amount: 180_000_000, date: '2026-06-01' },
      { label: 'تسویه', amount: 1_460_000_000, date: '2027-02-15' },
    ],
    reports: {
      cadence: 'ماهانه',
      count: 1,
      kpis: [
        { key: 'progress', label: 'پیشرفت', value: '۶۰٪' },
        { key: 'payments', label: 'پرداخت‌های انجام‌شده', value: '۰' },
        { key: 'next', label: 'سررسید بعدی', value: 'فروردین ۱' },
      ],
    },
    audit: [
      { label: 'ارزش‌گذاری', version: 'v2', date: '2026-02-10' },
      { label: 'به‌روزرسانی ضمانت', version: '', date: '2026-02-10' },
    ],
    coverageState: 'Normal',
  },
  {
    id: 'opp-2',
    title: 'توسعه کارگاه تولیدی — ضامن حقیقی',
    category: 'manufacturing',
    targetAmount: 1_500_000_000,
    raisedAmount: 900_000_000,
    durationMonths: 18,
    repaymentPlan: 'MIXED',
    grossAPR: 26,
    netAPR: 22,
    GI: 2,
    guaranteePack: [
      { type: 'ضامن حقیقی', verified: true, coverageLevel: 100 },
    ],
    dossier: [
      { key: 'identity', label: 'احراز هویت', done: true, updatedAt: '2026-01-08' },
      { key: 'collateral', label: 'ثبت ضمانت', done: false, updatedAt: '' },
      { key: 'valuation', label: 'ارزش‌گذاری', done: true, updatedAt: '2026-01-09' },
      { key: 'contract', label: 'قرارداد آماده', done: true, updatedAt: '2026-01-14' },
    ],
    events: [
      { label: 'ثبت', date: d(38) },
      { label: 'تأیید', date: d(35) },
      { label: 'شروع تأمین', date: d(25) },
      { label: 'گزارش ۱', date: d(5) },
      { label: 'تسویه', date: '' },
    ],
    cashflowPreview: [
      { label: 'شروع تأمین', amount: 0, date: d(25) },
      { label: 'میان‌دوره', amount: 200_000_000, date: '2026-08-01' },
      { label: 'میان‌دوره', amount: 200_000_000, date: '2027-02-01' },
      { label: 'تسویه', amount: 1_325_000_000, date: '2027-08-15' },
    ],
    reports: {
      cadence: 'ماهانه',
      count: 1,
      kpis: [
        { key: 'progress', label: 'پیشرفت', value: '۶۰٪' },
        { key: 'payments', label: 'پرداخت‌های انجام‌شده', value: '۰' },
        { key: 'next', label: 'سررسید بعدی', value: 'مرداد ۱' },
      ],
    },
    audit: [
      { label: 'ارزش‌گذاری', version: 'v1', date: '2026-01-09' },
      { label: 'ثبت قرارداد', version: '', date: '2026-01-14' },
    ],
    coverageState: 'Normal',
  },
  {
    id: 'opp-3',
    title: 'سرمایه در گردش پشتیبانی‌شده با طلا — ۶ ماه',
    category: 'trade',
    targetAmount: 500_000_000,
    raisedAmount: 500_000_000,
    durationMonths: 6,
    repaymentPlan: 'BALLOON',
    grossAPR: 20,
    netAPR: 17,
    GI: 4,
    guaranteePack: [
      { type: 'طلا', verified: true, valuationDate: '2026-02-01', coverageLevel: 110 },
    ],
    dossier: [
      { key: 'identity', label: 'احراز هویت', done: true, updatedAt: '2026-01-20' },
      { key: 'collateral', label: 'ثبت ضمانت', done: true, updatedAt: '2026-02-01' },
      { key: 'valuation', label: 'ارزش‌گذاری', done: true, updatedAt: '2026-02-01' },
      { key: 'contract', label: 'قرارداد آماده', done: true, updatedAt: '2026-02-05' },
    ],
    events: [
      { label: 'ثبت', date: d(25) },
      { label: 'تأیید', date: d(22) },
      { label: 'شروع تأمین', date: d(15) },
      { label: 'گزارش ۱', date: d(2) },
      { label: 'تسویه', date: '' },
    ],
    cashflowPreview: [
      { label: 'شروع تأمین', amount: 0, date: d(15) },
      { label: 'تسویه', amount: 542_500_000, date: '2026-08-15' },
    ],
    reports: {
      cadence: 'ماهانه',
      count: 1,
      kpis: [
        { key: 'progress', label: 'پیشرفت', value: '۱۰۰٪' },
        { key: 'payments', label: 'پرداخت‌های انجام‌شده', value: '۰' },
        { key: 'next', label: 'سررسید بعدی', value: 'مرداد ۱۵' },
      ],
    },
    audit: [
      { label: 'ارزش‌گذاری', version: 'v2', date: '2026-02-01' },
      { label: 'به‌روزرسانی ضمانت', version: '', date: '2026-02-01' },
    ],
    coverageState: 'Normal',
  },
  {
    id: 'opp-4',
    title: 'تأمین تجهیزات — وثیقه دستگاه',
    category: 'technology',
    targetAmount: 800_000_000,
    raisedAmount: 400_000_000,
    durationMonths: 12,
    repaymentPlan: 'MONTHLY',
    grossAPR: 24,
    netAPR: 20,
    GI: 2.5,
    guaranteePack: [
      { type: 'دستگاه', verified: true, valuationDate: '2026-01-15', coverageLevel: 95 },
    ],
    dossier: [
      { key: 'identity', label: 'احراز هویت', done: true, updatedAt: '2026-01-12' },
      { key: 'collateral', label: 'ثبت ضمانت', done: true, updatedAt: '2026-01-15' },
      { key: 'valuation', label: 'ارزش‌گذاری', done: true, updatedAt: '2026-01-15' },
      { key: 'contract', label: 'قرارداد آماده', done: false, updatedAt: '' },
    ],
    events: [
      { label: 'ثبت', date: d(35) },
      { label: 'تأیید', date: d(32) },
      { label: 'شروع تأمین', date: d(20) },
      { label: 'گزارش ۱', date: '' },
      { label: 'تسویه', date: '' },
    ],
    cashflowPreview: [
      { label: 'شروع تأمین', amount: 0, date: d(20) },
      { label: 'قسط ۱', amount: 80_000_000, date: '2026-04-01' },
      { label: 'قسط ۲', amount: 80_000_000, date: '2026-05-01' },
      { label: 'تسویه', amount: 640_000_000, date: '2027-02-20' },
    ],
    reports: {
      cadence: 'ماهانه',
      count: 0,
      kpis: [
        { key: 'progress', label: 'پیشرفت', value: '۵۰٪' },
        { key: 'payments', label: 'پرداخت‌های انجام‌شده', value: '۰' },
        { key: 'next', label: 'سررسید بعدی', value: '—' },
      ],
    },
    audit: [
      { label: 'ارزش‌گذاری', version: 'v1', date: '2026-01-15' },
      { label: 'به‌روزرسانی ضمانت', version: '', date: '2026-01-15' },
    ],
    coverageState: 'Normal',
  },
  {
    id: 'opp-5',
    title: 'ناوگان خودرو — وثیقه خودرو',
    category: 'transport',
    targetAmount: 1_200_000_000,
    raisedAmount: 600_000_000,
    durationMonths: 9,
    repaymentPlan: 'MONTHLY',
    grossAPR: 21,
    netAPR: 17.5,
    GI: 3.5,
    guaranteePack: [
      { type: 'خودرو', verified: true, valuationDate: '2026-02-01', coverageLevel: 90 },
    ],
    dossier: [
      { key: 'identity', label: 'احراز هویت', done: true, updatedAt: '2026-01-18' },
      { key: 'collateral', label: 'ثبت ضمانت', done: true, updatedAt: '2026-02-01' },
      { key: 'valuation', label: 'ارزش‌گذاری', done: true, updatedAt: '2026-02-01' },
      { key: 'contract', label: 'قرارداد آماده', done: true, updatedAt: '2026-02-08' },
    ],
    events: [
      { label: 'ثبت', date: d(30) },
      { label: 'تأیید', date: d(28) },
      { label: 'شروع تأمین', date: d(18) },
      { label: 'گزارش ۱', date: '' },
      { label: 'تسویه', date: '' },
    ],
    cashflowPreview: [
      { label: 'شروع تأمین', amount: 0, date: d(18) },
      { label: 'قسط ۱', amount: 133_000_000, date: '2026-04-15' },
      { label: 'قسط ۲', amount: 133_000_000, date: '2026-05-15' },
      { label: 'تسویه', amount: 934_000_000, date: '2026-11-18' },
    ],
    reports: {
      cadence: 'ماهانه',
      count: 0,
      kpis: [
        { key: 'progress', label: 'پیشرفت', value: '۵۰٪' },
        { key: 'payments', label: 'پرداخت‌های انجام‌شده', value: '۰' },
        { key: 'next', label: 'سررسید بعدی', value: 'فروردین ۱۵' },
      ],
    },
    audit: [
      { label: 'ارزش‌گذاری', version: 'v2', date: '2026-02-01' },
      { label: 'به‌روزرسانی ضمانت', version: '', date: '2026-02-01' },
    ],
    coverageState: 'Delayed',
  },
  {
    id: 'opp-6',
    title: 'سفته — تضمین تأمین‌کننده',
    category: 'trade',
    targetAmount: 600_000_000,
    raisedAmount: 600_000_000,
    durationMonths: 4,
    repaymentPlan: 'BALLOON',
    grossAPR: 18,
    netAPR: 15,
    GI: 2,
    guaranteePack: [
      { type: 'سفته', verified: true, coverageLevel: 100 },
    ],
    dossier: [
      { key: 'identity', label: 'احراز هویت', done: true, updatedAt: '2026-01-25' },
      { key: 'collateral', label: 'ثبت ضمانت', done: true, updatedAt: '2026-01-26' },
      { key: 'valuation', label: 'ارزش‌گذاری', done: true, updatedAt: '2026-01-26' },
      { key: 'contract', label: 'قرارداد آماده', done: true, updatedAt: '2026-01-28' },
    ],
    events: [
      { label: 'ثبت', date: d(28) },
      { label: 'تأیید', date: d(26) },
      { label: 'شروع تأمین', date: d(20) },
      { label: 'گزارش ۱', date: d(10) },
      { label: 'تسویه', date: '' },
    ],
    cashflowPreview: [
      { label: 'شروع تأمین', amount: 0, date: d(20) },
      { label: 'تسویه', amount: 630_000_000, date: '2026-06-20' },
    ],
    reports: {
      cadence: 'ماهانه',
      count: 2,
      kpis: [
        { key: 'progress', label: 'پیشرفت', value: '۱۰۰٪' },
        { key: 'payments', label: 'پرداخت‌های انجام‌شده', value: '۰' },
        { key: 'next', label: 'سررسید بعدی', value: 'خرداد ۲۰' },
      ],
    },
    audit: [
      { label: 'ارزش‌گذاری', version: 'v1', date: '2026-01-26' },
      { label: 'به‌روزرسانی ضمانت', version: '', date: '2026-01-26' },
    ],
    coverageState: 'Normal',
  },
  {
    id: 'opp-7',
    title: 'اعتبار اسنادی واردات — ضمانت بانکی',
    category: 'trade',
    targetAmount: 3_000_000_000,
    raisedAmount: 1_500_000_000,
    durationMonths: 8,
    repaymentPlan: 'MIXED',
    grossAPR: 16,
    netAPR: 13,
    GI: 5,
    guaranteePack: [
      { type: 'ضمانت‌نامه بانکی', verified: true, coverageLevel: 100 },
    ],
    dossier: [
      { key: 'identity', label: 'احراز هویت', done: true, updatedAt: '2026-01-02' },
      { key: 'collateral', label: 'ثبت ضمانت', done: true, updatedAt: '2026-01-05' },
      { key: 'valuation', label: 'ارزش‌گذاری', done: true, updatedAt: '2026-01-05' },
      { key: 'contract', label: 'قرارداد آماده', done: true, updatedAt: '2026-01-08' },
    ],
    events: [
      { label: 'ثبت', date: d(50) },
      { label: 'تأیید', date: d(45) },
      { label: 'شروع تأمین', date: d(35) },
      { label: 'گزارش ۱', date: d(15) },
      { label: 'گزارش ۲', date: d(5) },
      { label: 'تسویه', date: '' },
    ],
    cashflowPreview: [
      { label: 'شروع تأمین', amount: 0, date: d(35) },
      { label: 'میان‌دوره', amount: 500_000_000, date: '2026-06-01' },
      { label: 'تسویه', amount: 2_760_000_000, date: '2026-10-20' },
    ],
    reports: {
      cadence: 'ماهانه',
      count: 3,
      kpis: [
        { key: 'progress', label: 'پیشرفت', value: '۵۰٪' },
        { key: 'payments', label: 'پرداخت‌های انجام‌شده', value: '۰' },
        { key: 'next', label: 'سررسید بعدی', value: 'خرداد ۱' },
      ],
    },
    audit: [
      { label: 'ارزش‌گذاری', version: 'v2', date: '2026-02-12' },
      { label: 'به‌روزرسانی ضمانت', version: '', date: '2026-02-12' },
    ],
    coverageState: 'Normal',
  },
  {
    id: 'opp-8',
    title: 'ترکیب وثیقه ملکی و ضامن حقیقی',
    category: 'real_estate',
    targetAmount: 2_500_000_000,
    raisedAmount: 0,
    durationMonths: 24,
    repaymentPlan: 'MONTHLY',
    grossAPR: 19,
    netAPR: 16,
    GI: 4,
    guaranteePack: [
      { type: 'وثیقه ملکی', verified: true, valuationDate: '2026-02-01', coverageLevel: 80 },
      { type: 'ضامن حقیقی', verified: true, coverageLevel: 20 },
    ],
    dossier: [
      { key: 'identity', label: 'احراز هویت', done: true, updatedAt: '2026-02-10' },
      { key: 'collateral', label: 'ثبت ضمانت', done: true, updatedAt: '2026-02-10' },
      { key: 'valuation', label: 'ارزش‌گذاری', done: true, updatedAt: '2026-02-10' },
      { key: 'contract', label: 'قرارداد آماده', done: false, updatedAt: '' },
    ],
    events: [
      { label: 'ثبت', date: d(5) },
      { label: 'تأیید', date: '' },
      { label: 'شروع تأمین', date: '' },
      { label: 'گزارش ۱', date: '' },
      { label: 'تسویه', date: '' },
    ],
    cashflowPreview: [
      { label: 'شروع تأمین', amount: 0, date: '' },
      { label: 'قسط ۱', amount: 120_000_000, date: '' },
      { label: 'تسویه', amount: 2_380_000_000, date: '' },
    ],
    reports: {
      cadence: 'ماهانه',
      count: 0,
      kpis: [
        { key: 'progress', label: 'پیشرفت', value: '۰٪' },
        { key: 'payments', label: 'پرداخت‌های انجام‌شده', value: '۰' },
        { key: 'next', label: 'سررسید بعدی', value: '—' },
      ],
    },
    audit: [
      { label: 'ارزش‌گذاری', version: 'v2', date: '2026-02-10' },
      { label: 'به‌روزرسانی ضمانت', version: '', date: '2026-02-10' },
    ],
    coverageState: 'Normal',
  },
];
